on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: armyclusterregistry.azurecr.io
        username: ${{ secrets.acr_armyclusterregistry_username }}
        password: ${{ secrets.acr_armyclusterregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t armyclusterregistry.azurecr.io/darkarmycluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push armyclusterregistry.azurecr.io/darkarmycluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_darkarmycluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep darkarmy-clusteraa6e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace darkarmy-clusteraa6e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: darkarmy-clusteraa6e
        container-registry-url: armyclusterregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_armyclusterregistry_username }}
        container-registry-password: ${{ secrets.acr_armyclusterregistry_password }}
        secret-name: darkarmyclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: darkarmy-clusteraa6e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          armyclusterregistry.azurecr.io/darkarmycluster:${{ github.sha }}
        imagepullsecrets: |
          darkarmyclusdockerauth
